# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 1
builds:
  - goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s
      - -w
      - -X 'main.version=v{{ .Version }}'
      - -X 'main.commit={{ .FullCommit }}'
      - -X 'main.date={{ .CommitTimestamp }}'
      - -X 'main.builtBy="goreleaser"'
      - -X 'main.goVersion={{ .Env.GO_VERSION }}'
    mod_timestamp: "{{ .CommitTimestamp }}"
